### ISSUE TITLE
JS 对象字面量写法中的回调函数为何是字符串形式？

### ISSUE THREAD

**Issue by TechQuery** [cssobj/cssobj#1]
如题 —— https://cssobj.github.io/cssobj-demo/#demo5

直接声明为**匿名函数**不好吗？包在字符串里反而不方便了……

**Comment by futurist** [comment]
好主意！已更新。

之前使用`JSON.parse`,  要符合JSON规范。 现在改用`new Function`，直接在里面写代码吧。

See below commit:

https://github.com/cssobj/cssobj-demo/commit/48bfa0525c6b835cd58d6783575eafbe58b1023f


Please refresh demo page.

**Comment by TechQuery** [comment]
@futurist 作者效率啊！棒棒哒~
