### ISSUE TITLE
Comparison table to be updated

### ISSUE THREAD

**Issue by PhiLhoSoft** [cssobj/cssobj#11]
Your comparison table is interesting, but as I work on a comparison of several libraries to make a choice, I feel that some entries might be wrong.
For example, I think that Glamor do support IE8's media queries via some hook (not tested). And Fela supports changing rules / style at runtime, they even wrote an article on the topic: https://medium.com/@rofrischmann/styles-as-functions-of-state-1885627a63f7
Etc. I plan to gather more information as I test them, so I will propose some changes.

**Comment by futurist** [comment]
The compare table did should be corrected, and it's a base for people to select one.

If you can make some test and correct them, it's very valuable!

**Comment by futurist** [comment]
For contribution, I'm moving the compare table into a separate docs:

https://github.com/cssobj/cssobj/blob/master/docs/compare-table.md

Any update will be merged into that, thank you!

**Comment by futurist** [comment]
I do believe `glamor` don't have `@media hook for IE8`, I've been going through the docs and code, nothing at all, and they don't mention the `hook` exists. At this point the item in the compare table is right.

I rethink this issue, and the compare table, it's really need more work to do, and all the libs going to different way, so some times you cannot impose some feature they don't care in it's feature list. 

For example, `fela` never care IE8 (it use `Object.define` and many other ES5 methods which cannot perfectly polyfilled), `@media hook` become non-sense for this lib.

And many other good libs not included, like `j2c`.

The compare table beyond the work of cssobj, and I'm focusing on the code, not the table, that have far more work not belonged to this project.

So I close this issue, but keep the table, the url keep referenced, but I won't update it anymore.
