### ISSUE TITLE
Class name clash

### ISSUE THREAD

**Issue by PhiLhoSoft** [cssobj/cssobj#13]
I contribute to the [CSS-in-JS perf tests](https://github.com/hellofresh/css-in-js-perf-tests/) project, and CSSObj is part of the tested libraries.
In my [current branch](https://github.com/PhiLhoSoft/css-in-js-perf-tests/tree/complex-test-case) I simulate the case of a component with its own styling, with class names voluntarily clashing with class names used in the application itself. Ie. I use elements with `container` and `button` class names in the app, and the same names in a component used in the app.
After all, that's the main goal of the CSS-in-JS libraries: to avoid name clashing and to isolate CSS of components from the other CSS.

I probably use your library in a wrong way, because the generated names are the same in the app and in the component, so the display is bad...
The relevant code is at https://github.com/PhiLhoSoft/css-in-js-perf-tests/blob/complex-test-case/src/complex-test/cases/cssobj.js

I initialize the library with:

    const cssobjOptions = {
        local: true,
        plugins: [
            cssobjPluginLocalize(),
            cssobjPluginGencss({ indent: '\t', newLine: '\n' }),
        ]
    };
    const cssobj = cssobjCore(cssobjOptions);

I generate the styles as:

    const cssObjectA = cssobj(styleSheetA); // For the app
    const cssObjectC = cssobj(styleSheetC); // For the component

For the record, I also tried to create two `cssobj` instances, but I had the same results.

I get the mapped names via `cssObjectA.mapClass` and `cssObjectC.mapClass` functions.

The generated code looks like:
```
<div class=" container_13fcj6h1_">
    <section class=" itemContainer_13fcj6h1_">
        <header class=" title_13fcj6h1_">
            <h2>Main app</h2>
        </header>
<div class=" container_13fcj6h1_ regular">
    <span>Item A</span>
    <input type="checkbox" value="a" >Disable</input>
    <button class=" button_13fcj6h1_">x</button>
</div>
[....]
<div class=" container_13fcj6h1_ regular">
    <span>Item E</span>
    <input type="checkbox" value="e" >Disable</input>
    <button class=" button_13fcj6h1_">x</button>
</div>
        <button class=" button_13fcj6h1_">Update</button>
    </section>
[...]
</div>
```
Notice the `container_13fcj6h1_` class on the external div, and the same name on the div wrapping the components. Likewise, the global button is named `button_13fcj6h1_` and so are the component buttons.
Other libraries doesn't have this problem...

So, did I miss something in the setup or in the way to use the API?
Thank you for any insight.

Note; I saw I can workaround the issue by using custom decorations, but I wanted to know why the default suffixes aren't truly random as said in the docs.

**Comment by futurist** [comment]
If `factory = cssobjCore({})`, then every `factory(obj)` share a same **scope**.

If you want 2 **scope**, you have to call `factory2 = cssobjCore({})` again.

I don't look at the code in depth, but this maybe a clue?

**Comment by PhiLhoSoft** [comment]
Yes, I tried that too. As said above "*For the record, I also tried to create two `cssobj` instances, but I had the same results.*"

    const cssobjA = cssobjCore(cssobjOptions);
    const cssobjC = cssobjCore(cssobjOptions);

    const cssObjectA = cssobjA(styleSheetA);
    const cssObjectC = cssobjC(styleSheetC);

Looks like the random number generator had the same seed in the two instances.
Tried again with the latest version cssobj@1.1.2 but same collision.

**Comment by futurist** [comment]
The problem is the `cssobjOptions`, you have to include `cssobjPluginLocalize()` 2 times

**Comment by PhiLhoSoft** [comment]
Excellent. With the following code:

    const localA = cssobjPluginLocalize();
    const localC = cssobjPluginLocalize(); // Needs 2 instances
    const genCss = cssobjPluginGencss({ indent: '\t', newLine: '\n' });

    const cssobjA = cssobjCore({ local: true, plugins: [ localA, genCss ] });
    const cssobjC = cssobjCore({ local: true, plugins: [ localC, genCss ] });

    const cssObjectA = cssobjA(styleSheetA);
    const cssObjectC = cssobjC(styleSheetC);

the problem is gone.
I suppose it is not a problem in a real app, as the component will make its full instance itself.
Many thanks for your help.

**Comment by PhiLhoSoft** [comment]
Apparently, if I use this plugin, I don't need the `local: true`, or I have not understood the usage of this option.

**Comment by futurist** [comment]
please look at https://github.com/cssobj/cssobj/blob/master/lib/cssobj.js  and you should understand the `local: true`,  it's not exist in core.
