### ISSUE TITLE
Duplicate identifier 'lastVal'.

### ISSUE THREAD

**Issue by sw-creed** [cssobj/cssobj#17]
Getting an error in the index.d.ts file:
**Duplicate identifier 'lastVal'.**

```typescript
    interface Node {
      children: Object;
      key: string;
      obj: Object;
      parent: Object;
      diff?: Object;
      omRule?: Object[];
      parentRule?: any;
      rawVal?: Object;
      lastVal?: Object;   // ONE
      lastRaw?: Object;
      lastVal?: Object;   // TWO
      prevVal?: any;
      prop?: Object;
      selPart?: string[];
      selText?: string;
      selTextPart?: string;
      groupText?: string;
      at?: string;
      type?: string;
    }
```

https://github.com/cssobj/cssobj/blob/master/index.d.ts

**Comment by futurist** [comment]
fixed via https://github.com/cssobj/cssobj/commit/d9e745c66fa2da272e2e73614bd52e082b9cb83e

**Comment by futurist** [comment]
I don't use TS, any issue regarding TS, please kindly fill a PR and have it tested on your side. thank you!

**Comment by sw-creed** [comment]
Kool.  I modified the file locally and got it to work before I posted the thread.  Everything else is working great in my Angular 4 app.  Thanks alot!!!
