### ISSUE TITLE
Does it work with iframe?

### ISSUE THREAD

**Issue by yellow1912** [cssobj/cssobj#3]
I wonder if this works with iframe content given that it loads the content from the same origin (domain)?
With jquery I can call .css method on an element inside iframe like this

$('#iframe').contents().find('#widget-1').css('color', 'red;);

**Comment by futurist** [comment]
Added this feature, please see test:

https://github.com/cssobj/cssobj/blob/master/test/spec/frame.js

And doc:

https://github.com/cssobj/cssobj#--iframe-support

**Comment by yellow1912** [comment]
This is just awesome and seems to work well, thank you for your top notch support, once I'm done I will make sure to link back to cssobj so more people will know about it.

I also tested multiple selectors, seem to works well as well.:

`var obj = {
  '#widget-1,.widget-1': {
    // will prefix for current browser
    backgroundColor: 'blue'
  }
}`

In later code when I need to update the style, I do

obj[ '#widget-1,.widget-1'].backgroundColor = 'yellow' which also works.

Only 1 last question: I want to use cssobj to do live website editor, where a user can change certain settings on a control bar and see the changes applied in real time. I used jQuery css() method before but that doesnt work for pseudo elements so I found out about cssobj. Looking at the code I assume that cssobj only applies the changes based on the diff of the obj before and after so it should be safe in term of performance?

**Comment by futurist** [comment]
yes it's only apply diff of JS objects, you can check the performance below:

https://futurist.github.io/cssobj-less/

It's live updating the LESS code based on CSSOBJ, which have far more complicated computing with mixins, variables, and functions.

My next plan is to implement the diff instead of `getter` and `setter` of ES5, that way it won't loop between objects, will gain improved performance.

Also, contribution is welcome :)

**Comment by TechQuery** [comment]
@yellow1912 

I writed a [polyfill](https://github.com/TechQuery/iQuery.js/blob/master/source/extension/iCSS.js#L70) for `window.getMatchedCSSRules()` (Google Chrome private API), just like `window.getComputedStyle()`, it also accepts a second argument to return a **Style Object of Pseudo**.

**Comment by futurist** [comment]
Since no furthur feedback for this issue, seems it's working, close it for now.
