### ISSUE TITLE
Do we handle multiple backgrounds?

### ISSUE THREAD

**Issue by yellow1912** [cssobj/cssobj#6]
I wonder if we are handling multiple values for properties that accept multiple values such as backgrounds?

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Using_CSS_multiple_backgrounds

Other properties are box-shadow, etc...

**Comment by futurist** [comment]
Assume below css:
```css
.myclass {
  background: background1, background 2, ..., backgroundN;
}
```

converted as:

```javascript
{
'.myclass': {
  background: 'background1, background 2, ..., backgroundN'
}
}
```

So the link you provide can be converted using [online-converter](http://convertcssobj-futurist.rhcloud.com/) as:
```javascript
{
  '.multi_bg_example': {
    width: '100%',
    height: '400px',
    backgroundImage: 'url(https://mdn.mozillademos.org/files/11305/firefox.png), url(https://mdn.mozillademos.org/files/11307/bubbles.png), linear-gradient(to right, rgba(30, 75, 115, 1), rgba(255, 255, 255, 0))',
    backgroundRepeat: 'no-repeat, no-repeat, no-repeat',
    backgroundPosition: 'bottom right, left, right',
    background: '-moz-linear-gradient(to right, rgba(30, 75, 115, 1), rgba(255, 255, 255, 0)), -webkit-gradient(to right, rgba(30, 75, 115, 1), rgba(255, 255, 255, 0)), -ms-linear-gradient(to right, rgba(30, 75, 115, 1), rgba(255, 255, 255, 0)), linear-gradient(to right, rgba(30, 75, 115, 1), rgba(255, 255, 255, 0))'
  }
}
```

Am I understandarding right about your question?

**Comment by yellow1912** [comment]
Yup.

So for example normally I may have to do all the conversion to string first the pass to cssobj, but it would be very nice if say I can pass in an array and cssobj automatically knows what to do?

**Comment by futurist** [comment]
Please see the wiki for [Property-with-multiple-values](https://github.com/cssobj/cssobj/wiki/Property-with-multiple-values), that how array is parsed by cssobj.

Also, the [Input-Object-Format](https://github.com/cssobj/cssobj/wiki/Input-Object-Format) may help.

**Comment by yellow1912** [comment]
Maybe I'm mis-understanding how it should work, but:

1. I tested with backgroundImage and set an array to it and it seems to work correctly
2. I tested with backgroundSize and backgroundRepeat but they don't see to handle array correctly and seem to take only the last element of the array?

**Comment by futurist** [comment]
@yellow1912 yes only the last element of array with **valid css value** will be applied, it's not cssobj, it's CSS rules.

```javascript
{ p: { backgroundRepeat: ['no-repeat', 'repeat-x']  } }
```
 will result as:

```css
p { background-repeat: no-repeat; background-repeat: repeat-x;  }
```

Please read above CSS rules, and found your poblem from that.

cssobj will only do the conversion to CSS, and please check your CSS result with this tool:

https://github.com/cssobj/cssobj-plugin-csstext

**Comment by yellow1912** [comment]
Huhm, I have tried this 

backgroundRepeat: ["no-repeat", "repeat-x"]

However, when I inspect the element (in Chrome), I get only the repeat-x :(

**Comment by yellow1912** [comment]
After using the csstext plugin it seems like actually backgroundImage also being applied incorrectly

This is what I get with csstext:

#nl-widget-container, .nl-widget-container { background-image: url("/assets/images/sleeveless-romantic-chiffon-asian-fashion-dress-with-pleats-pink-04_1234567890_medium.jpg"); background-repeat: repeat-x; background-size: 60px 60px; }

As you can see with the imgur image above, each of the property is an array of 2 elements but what I get is a a single value instead of multiple?

**Comment by futurist** [comment]
@yellow1912 what's your point of usage? array as value lead to **Cascading of Style Sheet**, which mean, 

**What's CSS (Cascading of Style Sheet) ?**:
```css
p {color: red; color: blue; }
```

If you have 2 value of color, the style cascaded, only the last one: **red** will be applied.

https://drafts.csswg.org/css2/cascade.html#cascade

But, what's your expectation of code `color: ['red', 'blue']` result in? Please tell me to discuss this.

**Comment by yellow1912** [comment]
I think I was confused by how the array should work. You are right, I should just join them by myself then pass to cssobj instead.
