### ISSUE TITLE
Whether allow node.prop accept invalid CSS if it's start with $

### ISSUE THREAD

**Issue by futurist** [cssobj/cssobj#7]
See PR https://github.com/cssobj/cssobj-core/pull/1

Think below code:

``` javascript
cssobj({
  p: { $test: true, font: 123, color: null }
})
```

The `$test` prop will be dropped in **node.prop** object, since `true` cannot pass the condition:

``` javascript
if( isValidCSSValue(val) ) ...
```

So the resulting v-node is:

```
{
  ...
  rawVal: { $test:[true], font: [123], color: [null] },
  prop: { font: [123] }
  ...
}
```

User can check the `node.rawVal` object to get the `$test` value.

The Different between `rawVal` and `prop` is: the first is **before** value plugins, the latter is value **after** all value plugins, in addition, ensure it's **Valid CSS**

This branch is allow `node.prop` accept **invalid** CSS values if it's start with "$":

https://github.com/cssobj/cssobj-core/blob/prop-allow-all-%24/lib/cssobj-core.js#L287

This will allow above code resulting as below:

```
{
  ...
  rawVal: { $test:[true], font: [123], color: [null] },
  prop: { $test:[true], font: [123] }
  ...
}
```

Does this make sense? Is there any side effects?

**Comment by PhiLhoSoft** [comment]
Well, I fail to see how this would be used. Adding some real use case for this feature might help...

**Comment by futurist** [comment]
`node.rawVal` will accept any value, even it's not valid CSS value. that's the meaning of `raw`
