### ISSUE TITLE
cssobj terminology (glossary, naming)

### ISSUE THREAD

**Issue by futurist** [cssobj/cssobj#8]
I'm revising the docs, as a preparing, please suggesting below terminology (glossary, naming):

**Sample Object**

``` javascript
var obj = {
  div: {
    $test: true,
    font: 123,
    color: function(){ return 'red' },
    p: {
      height: 10
    }
  }
}
```

Please suggesting below naming:

| word | candidates | remark |
| --- | --- | --- |
| **obj** | **Source JS Object** |  |
| **div** | **Selector** |  |
| **$test** | **Meta Property** | directive? |
| **font** | **Property Name** |  |
| **123** | **Property Value** |  |
| **function ()<br>{ return 'red' }** | **Value Function** | maybe **Function Value**?<br>but it's confused with JS. |
| **p** | **Nested Selector** |  |

More use case and naming suggests are welcome!

**Comment by PhiLhoSoft** [comment]
Looks good. I prefer "value function" anyway, as "function returning a value".

**Comment by PhiLhoSoft** [comment]
Additional name:
`color: red;`
ie. the combination of a property and a value, is called a *rule*.
Maybe there should be something about classes too...

**Comment by futurist** [comment]
According to [CSS Spec](https://www.w3.org/TR/CSS1/#css1-properties), this should be called "Property",  `color` is `Property name`, the `red` is `Property value`.

The whole `div {}` part is called **a rule**
