### ISSUE TITLE
result.update() does not work with an !important

### ISSUE THREAD

**Issue by showyweb** [cssobj/cssobj#9]
cssobj.update() does not work with an !important
To work around this error, it is necessary to use the following code:
```javascript
var save_s_obj = result.obj[selector];
delete result.obj[selector];
result.update();
result.obj[selector] = save_s_obj;
result.obj[selector][prop] = val + " !important";
result.update();
```

**Comment by futurist** [comment]
@showyweb Please check [0.6.3](https://github.com/cssobj/cssobj/releases/tag/0.6.3)

This bug should be fixed now.

**Comment by showyweb** [comment]
Thank you, the bug is fixed! Your library is the best available.

**Comment by showyweb** [comment]
When the code below using cssobj v0.6.3, Google Chrome 54.0.2840.87 m (64-bit) stops responding for a long time.
```javascript
result.obj[selector]['background-image'] =  "url(data:image/png;base64,iVBORw0..."; //Without !important
result.update();
```
Discovered that hangs when the regular expression in the cssobj-0.6.3/dist/cssobj.iife.js file on line 663

We managed to fix by replacing the regular expression `/(.*)!(important)\s*$/i` on `/^(.*)!(important)\s*$/i`

**Comment by futurist** [comment]
Oh, that !important rule is really important!

Updated as [0.6.5](https://github.com/cssobj/cssobj/releases/tag/0.6.5)

Also, you can check [Input format rule](https://github.com/cssobj/cssobj/wiki/Input-Object-Format#4-css-property-and-value-rule)

`result.obj[selector]['background-image']` should be 

```js
result.obj[selector]['backgroundImage']
```
